import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

const Navbar = () => {
  return (
    <nav className="bg-gray-800 shadow-lg">
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex-shrink-0">
            <Link href="/" className="text-white text-lg font-semibold">
              Your Logo
            </Link>
          </div>
          {/* Navigation Links */}
          <div className="hidden md:block">
            <ul className="flex space-x-4">
              <Link href="/" className='text-white hover:text-gray-300'>
                Home
              </Link>
              <Link href="/about" className='text-white hover:text-gray-300'>
                About
              </Link>
              <a href="https://www.youtube.com/watch?v=QaFg4wbxuHI&t=34s" className='text-white hover:text-gray-300'>
                Portal
              </a>
              <Link href="/contact" className='text-white hover:text-gray-300'>
                Contact
              </Link>

            </ul>
          </div>
          {/* Mobile Menu Button */}
          <div className="md:hidden">
            <button className="text-white focus:outline-none">
              <svg
                className="h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 6h16M4 12h16m-7 6h7"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

const Footer = () => {
  return (
    <footer className="bg-gray-800 text-white py-6">
      <div className="container mx-auto flex justify-between items-center">
        <div>
          <p className="font-bold text-lg">Your Company</p>
          <p className="text-sm">Address, City, Country</p>
        </div>
        <div>
          <p className="text-sm">Follow Us:</p>
          <div className="flex space-x-2">
            <a href="#" className="text-white hover:text-gray-300">
              Twitter
            </a>
            <a href="#" className="text-white hover:text-gray-300">
              Facebook
            </a>
            <a href="#" className="text-white hover:text-gray-300">
              Instagram
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <style>{inter.css}</style>
      </head>
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export const metadata = {
  title: 'Portal App',
  description: 'Generated by create next app',
};

export default RootLayout;
